<?php
session_start();
require('fpdf/fpdf.php');
include('funclib.php');
include('../config/dbconnect.php');
require_once "../config/funlib/login_functions.php";
error_reporting(0);
//print_r($_GET);
//print_r($_SESSION);
if( isset($_GET['id']) && ( isLogin() != null) )
{
		$no = $_GET['id'];
		$no = base64_decode($no);
		if($_SESSION['sec_access_code'] == $no)
		{
			unset($_SESSION['sec_access_code']);
			//echo "Legal Access";
		}
		else
		{
			die("Illegal Access");
		}
}


$stud_id = $_SESSION['user_ref_id'];
$view_query = "SELECT `student`.`id`,`student`.`category`,`student`.`prn`,`student`.`local_address`,`student`.`mobile_no`,`student`.`email`,`student`.`name`,`student`.`current_semester`,`student`.`department`,`department`.`department_name` FROM `student` LEFT JOIN `department` ON `department`.`id` = `student`.`department`  WHERE `student`.`id`='$stud_id'";
$result_view= mysqli_query($dbcon,$view_query) or die(mysqli_error($dbcon));

$row2 = mysqli_fetch_assoc($result_view);
$student_id = $row2['id'];
$name = $row2['name'];
$prn = $row2['prn'];
$category = $row2['category'];
$adress = $row2['local_address'];
$email = $row2['email'];
$mob = $row2['mobile_no'];
//$batch = $row2['admission_year'];
$semester = $row2['current_semester'];
$branch = $row2['department_name'];
$department_id = $row2['department'];
//$gender = $row2['gender'];

if($semester%2 == 0)
	$eo = "even";
else
	$eo = "odd";



//die("LAter...");
class PDF extends FPDF
{
	protected $B = 0;
	protected $I = 0;
	protected $U = 0;
	protected $HREF = '';

	// Page header
	function Header()
	{

		
		
	}
	// Page footer
	function Footer()
	{
		// Position at 1.5 cm from bottom
		$this->SetY(-10);
		// Arial italic 8
		$this->SetFont('Arial','BI',8);
		// Page number
		$this->Cell(75,10,'Auto Generated By MIS Developed Software Development Cell',0,0,'L');
		$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'R');
	}

	function WriteHTML($html)
	{
		// HTML parser
	$html = str_replace("\n",' ',$html);
		$a = preg_split('/<(.*)>/U',$html,-1,PREG_SPLIT_DELIM_CAPTURE);
		foreach($a as $i=>$e)
		{
			if($i%2==0)
			{
				// Text
				if($this->HREF)
					$this->PutLink($this->HREF,$e);
				else
					$this->Write(5,$e);
			}
			else
			{
				// Tag
				if($e[0]=='/')
					$this->CloseTag(strtoupper(substr($e,1)));
				else
				{
					// Extract attributes
					$a2 = explode(' ',$e);
					$tag = strtoupper(array_shift($a2));
					$attr = array();
					foreach($a2 as $v)
					{
						if(preg_match('/([^=]*)=["\']?([^"\']*)/',$v,$a3))
							$attr[strtoupper($a3[1])] = $a3[2];
					}
					$this->OpenTag($tag,$attr);
				}
			}
		}
	}


	function BasicTable($header, $data)
	{



		
	}


	function OpenTag($tag, $attr)
	{
		// Opening tag
		if($tag=='B' || $tag=='I' || $tag=='U')
			$this->SetStyle($tag,true);
		if($tag=='A')
			$this->HREF = $attr['HREF'];
		if($tag=='BR')
			$this->Ln(5);
	}

	function CloseTag($tag)
	{
		// Closing tag
		if($tag=='B' || $tag=='I' || $tag=='U')
			$this->SetStyle($tag,false);
		if($tag=='A')
			$this->HREF = '';
	}

	function SetStyle($tag, $enable)
	{
		// Modify style and select corresponding font
		$this->$tag += ($enable ? 1 : -1);
		$style = '';
		foreach(array('B', 'I', 'U') as $s)
		{
			if($this->$s>0)
				$style .= $s;
		}
		$this->SetFont('',$style);
	}

	function PutLink($URL, $txt)
	{
		// Put a hyperlink
		$this->SetTextColor(0,0,255);
		$this->SetStyle('U',true);
		$this->Write(5,$txt,$URL);
		$this->SetStyle('U',false);
		$this->SetTextColor(0);
	}


}


// Instanciation of inherited class
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true,6);
$pdf->SetTopMargin(5);
	$pdf->SetFont('Arial','B',8);
	$pdf->Cell(190,7,"S01",0,0,'R');
	// Logo
	$pdf->Image('logo.png',8,16,195);
	$pdf->Image('photo.png',170,52,30,40);
	// Arial bold 15
	/*$pdf->SetFont('Arial','B',15);
	// Move to the right
	$pdf->Cell(30);
	// Title
	$pdf->Cell(150,10,'Government College of Engineering, Jalgaon',1,0,'C');*/
	// Line break
	$pdf->Ln(34);
	$pdf->SetFont('Arial','B',14);

	$pdf->SetTextColor(255);
// Background color
$pdf->SetFillColor(0,0,0);
// Title
$pdf->Cell(190,7,"EXAM REGISTRATION FORM",0,1,'C',true);
$pdf->SetFont('Arial','',9);
$pdf->SetTextColor(0);


//$i=1;
	//$pdf->Cell(15,10,'Name : '.$m_pname,0,0);
	$html = 'Name : <b>'.$m_pname.'</b><br>'
	.'Personal Contact Number : <b>'.$m_pc_no.'</b><br>'
	.'Parents Contact Number : <b>'.$m_psc_no.'</b><br>'
	.'Email : <b>'.$m_pemail.'</b><br>'
	.'Category : <b>'.$m_event.'</b>'
	.'      Gender : <b>'.$m_pgender.'</b><br>'
	.'Physically Handicapped : <b>'.$m_ph.'</b>'
	.'     Defence : <b>'.$m_def.'</b><br>'
	.'J & K / North Eastern Candidate : <b>'.$m_jk.'</b><br>'
	.'Current Year & Branch : <b>'.$m_pbranch.'</b><br>'
	.'Permanent Address : <b>'.$m_padd.'</b><br>'
	.'Local Address : <b>'.$m_ladd.'</b><br>'
	.'Latest Semester SGPA : <b>'.$m_pclgname.'</b><br>';
	$html3='To,<br><b>The Dean Academics,</b><br>Government College of Enginnering, Jalgaon - 425002<br><br><b>Respected Sir,</b><br>

        I request permission to register myself as a
<br>
<b>regular</b> student in the '.$eo.' semester of B.TECH.
<br>
during the academic year Summer 2017 and pay
<br>
herewith the prescribed fees Rs ________<br><br><br>
<b>Date : 11/01/2017                          Signature of Candidate</b><br>';

	$html2='           I have read all the rules of hostel admission and after understanding these rules thoroughly, I have filled in the application form for admission of current year. The information given by me in my application is true to the best of my knowledge and belief. I understand that if any of the statements made by me in the application form or any information/documents supplied by me in connection with my admission is found to be false or incorrect at any stage, my admission will be cancelled. I hereby agree that I will be bound to all Rules, Acts and Laws set by State Government. I hereby undertake that, I will follow all the rules and regulation of the hostel, failing which will be liable for disciplinary action.';

	$pdf->WriteHTML($html3);
	$pdf->Cell(0,1," ",'B',1);
	//$pdf->WriteHTML($html);
	/*$pdf->Cell(0,10,'Email : '.$m_pemail,0,1);
	$pdf->Cell(0,10,'Contact Number : '.$m_pc_no,0,1);
	$pdf->Cell(0,10,'Category : '.$m_event,0,1);
	$pdf->Cell(0,10,'Gender : '.$m_pgender,0,1);
	$pdf->Cell(0,10,'CGPA : '.$m_pclgname,0,1);
	$pdf->Cell(0,10,'Current Year & Branch : '.$m_pbranch,0,1);
	*/
	$pdf->Ln(1);
	$pdf->Cell(12,5,"Name : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(80,5,$name,0,0,'L');
	$pdf->SetFont('');	
	
	$pdf->Cell(12,5,"Email : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(80,5,$email,0,1,'L');
	$pdf->SetFont('');
	
	$pdf->Cell(12,5,"PRN : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(80,5,$prn,0,0,'L');
	$pdf->SetFont('');
	
	$pdf->Cell(42,5,"Candidate Contact Number : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(40,5,$mob,0,1,'L');
	$pdf->SetFont('');
	
	$pdf->Cell(22,5,"Semester : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(70,5,$semester,0,0,'L');
	$pdf->SetFont('');
	
	$pdf->Cell(22,5,"Depaerment : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(70,5,$branch,0,1,'L');
	$pdf->SetFont('');
	

	/*
	$pdf->Cell(20,5,"Adm. Batch : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(72,5,"",0,0,'L');
	$pdf->SetFont('');
	*/
	$pdf->Cell(15,5,"Category : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(20,5,$category,0,0,'L');
	$pdf->SetFont('');
	/*$pdf->Cell(15,5,"Gender : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(15,5,$gender,0,1,'L');
	$pdf->SetFont('');
	*/
	$pdf->Cell(15,5,"Address : ",0,0,'L');
	$pdf->SetFont('','BI');
	$pdf->Cell(180,5,$adress,0,1,'L');
	$pdf->SetFont('');
	$pdf->Ln(1);
	/*$pdf->Cell(60,5,"Details of Previous Result : ",0,0,'L');
	$pdf->SetFont('','B');
	$pdf->Cell(35,5,"Examination",1,0,'C');
	$pdf->Cell(35,5,"Semester",1,0,'C');
	$pdf->Cell(35,5,"Result",1,1,'C');
	$pdf->SetFont('');
	$pdf->Cell(60,5,"",0,0,'C');
	$pdf->Cell(35,5,"RE-EXAM SUMMER17",1,0,'C');
	$pdf->Cell(35,5,"VI",1,0,'C');
	$pdf->Cell(35,5,"Pass",1,1,'C');*/
	$pdf->SetFont('','B');
	$pdf->Cell(18,6,"Enclosure :",0,0,'L');
	$pdf->SetFont('');
	$pdf->Cell(0,6,"Photo copies of previous result (__Copies)",0,1,'L');
	$pdf->SetFillColor(200,200,200);
	$pdf->SetFont('Arial','BI',10);
	$pdf->Cell(190,6,"COURSES REGISTERED",0,1,'C',true);
	$pdf->SetFont('Arial','',9);
	$pdf->SetTextColor(0);
	$pdf->SetFont('','B');
	$pdf->Cell(190,6,"REGULAR COURSES REGISTERED",0,1,'C',true);
	$pdf->Cell(18,6,"Sr. No.",1,0,'C');
	$pdf->Cell(30,6,"Course Code",1,0,'C');
	$pdf->Cell(90,6,"Course Name",1,0,'L');
	$pdf->Cell(18,6,"Credits",1,0,'C');
	$pdf->Cell(34,6,"Course Type",1,1,'C');
	$pdf->SetFont('');
	$i=1;
	$query = "SELECT course.id, course.course_code, course.course_name, course.credits,course_type.name FROM  ses_conf,exam_registration,course LEFT JOIN course_type ON course.course_type_id = course_type.id WHERE exam_registration.sesn_id = ses_conf.current_session AND `ses_conf`.`id` = '1' AND `exam_registration`.`stud_id`='$stud_id' AND `exam_registration`.`course_id` = `course`.`id` AND `exam_registration`.`regular_flag`= '1' ";
	if ($res = mysqli_query($dbcon,$query)) {
		$i = 1;
		while($row = mysqli_fetch_assoc($res))
		{
			$pdf->Cell(18,6,$i,1,0,'C');
			$pdf->Cell(30,6,$row['course_code'],1,0,'C');
			$pdf->Cell(90,6,$row['course_name'],1,0,'L');
			$pdf->Cell(18,6,$row['credits'],1,0,'C');
			$pdf->Cell(34,6,$row['name'],1,1,'C');
			$i=$i+1;	
		}
	}
	$pdf->Cell(190,6,"BACKLOG COURSES REGISTERED(*If ANY)",0,1,'C',true);
	$pdf->Cell(18,6,"Sr. No.",1,0,'C');
	$pdf->Cell(30,6,"Course Code",1,0,'C');
	$pdf->Cell(90,6,"Course Name",1,0,'L');
	$pdf->Cell(18,6,"Credits",1,0,'C');
	$pdf->Cell(34,6,"Course Type",1,1,'C');
	$pdf->SetFont('');
	$i=1;
	$query1 = "SELECT course.id, course.course_code, course.course_name, course.credits,course_type.name FROM  ses_conf,exam_registration,course LEFT JOIN course_type ON course.course_type_id = course_type.id WHERE exam_registration.sesn_id = ses_conf.current_session AND `ses_conf`.`id` = '1' AND `exam_registration`.`stud_id`='$stud_id' AND `exam_registration`.`course_id` = `course`.`id` AND `exam_registration`.`regular_flag`= '0' ";
	if ($res1 = mysqli_query($dbcon,$query1)) {
		$i = 1;
		while($row1 = mysqli_fetch_assoc($res1))
		{
			$pdf->Cell(18,6,$i,1,0,'C');
			$pdf->Cell(30,6,$row1['course_code'],1,0,'C');
			$pdf->Cell(90,6,$row1['course_name'],1,0,'L');
			$pdf->Cell(18,6,$row1['credits'],1,0,'C');
			$pdf->Cell(34,6,$row1['name'],1,1,'C');
			$i=$i+1;	
		}
	}
	
	//$pdf->Ln();
	//$pdf->WriteHTML($html2);
	//$pdf->Ln(10);
	$pdf->Cell(30,6,"Date & Time : ",0,0,'L');
	$pdf->Cell(0,6,$pdate,0,1,'L');
	$pdf->Cell(0,6,"Place : Jalgaon",0,0,'L');
	$pdf->SetFont('','B');
	$pdf->Cell(0,6,"Signature of Candidate",0,1,'R');
	$pdf->SetFont('');
	$pdf->Cell(0,1," ",'B',1);
	$pdf->Cell(0,7,"For Office Use : ",0,1,'L');
	$pdf->Cell(120,6,"Receipt Amount : ",0,0,'L');
	$pdf->Cell(27,6,"Receipt No.",0,0,'L');
	$pdf->Cell(40,6,"",'B',1,'L');
	//$pdf->Cell(0,6,"Room Alloted : Room No.",0,1,'L');*/
	//$pdf->Ln(5);
	$pdf->SetFont('','B');
	$pdf->Cell(120,6,"Signature of Class Teacher",0,0,'L');
	$pdf->Cell(0,6,"Signature of Admission Clerk",0,1,'R');
	$pdf->SetFont('');

	$pdf->Output();
	
	?>